import os
import psycopg
from dotenv import load_dotenv

load_dotenv()


DATABASE_URL = (
    os.getenv("DATABASE_URL")
    or os.getenv("POSTGRES_URL")
    or os.getenv("POSTGRES_PRISMA_URL")
)

if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL / POSTGRES_URL is not configured"
    )


TABLES = [
    "users",
    "attendance",
    "faculty_attendance",
    "assignments",
    "submissions",
    "notices",
    "results",
    "fees",
    "placements",
    "timetable",
]


with psycopg.connect(DATABASE_URL) as conn:

    print("Connected to Neon PostgreSQL.")

    for table in TABLES:

        print(f"\nChecking {table}...")

        identity = conn.execute(
            """
            SELECT a.attidentity
            FROM pg_attribute a
            JOIN pg_class c
              ON c.oid = a.attrelid
            WHERE c.relname = %s
              AND a.attname = 'id'
              AND a.attnum > 0
              AND NOT a.attisdropped
            """,
            (table,)
        ).fetchone()


        if not identity:

            print(
                f"  WARNING: id column not found."
            )

            continue


        if identity[0] == "":

            print(
                f"  Adding identity to {table}.id..."
            )

            conn.execute(
                f'''
                ALTER TABLE "{table}"
                ALTER COLUMN id
                ADD GENERATED BY DEFAULT AS IDENTITY
                '''
            )

        else:

            print(
                f"  Already identity: {identity[0]}"
            )


        sequence = conn.execute(
            """
            SELECT pg_get_serial_sequence(
                %s,
                'id'
            )
            """,
            (table,)
        ).fetchone()[0]


        if sequence:

            maximum = conn.execute(
                f'''
                SELECT COALESCE(MAX(id), 0)
                FROM "{table}"
                '''
            ).fetchone()[0]


            if maximum:

                print(
                    f"  Synchronizing sequence to {maximum}..."
                )

                conn.execute(
                    """
                    SELECT setval(
                        %s::regclass,
                        %s,
                        true
                    )
                    """,
                    (
                        sequence,
                        int(maximum)
                    )
                )


    print("\nAdding submission file columns...")


    conn.execute(
        """
        ALTER TABLE submissions
        ADD COLUMN IF NOT EXISTS file_data BYTEA
        """
    )


    conn.execute(
        """
        ALTER TABLE submissions
        ADD COLUMN IF NOT EXISTS mime_type TEXT
        """
    )


    conn.execute(
        """
        ALTER TABLE submissions
        ADD COLUMN IF NOT EXISTS file_size BIGINT
        """
    )


    conn.execute(
        """
        ALTER TABLE submissions
        ADD COLUMN IF NOT EXISTS student_notes TEXT
        """
    )


    conn.commit()


print("\n========================================")
print("Neon schema repair complete!")
print("========================================")