import os
from datetime import datetime, date
from typing import Optional

import psycopg
from psycopg.rows import dict_row
from fastapi import FastAPI, HTTPException, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from pydantic import BaseModel


# ============================================================
# DATABASE
# ============================================================

DATABASE_URL = (
    os.getenv("DATABASE_URL")
    or os.getenv("POSTGRES_URL")
    or os.getenv("POSTGRES_PRISMA_URL")
)

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL / POSTGRES_URL is not configured")


app = FastAPI(
    title="UniSphere University Portal API - PostgreSQL"
)


app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def db():
    return psycopg.connect(
        DATABASE_URL,
        row_factory=dict_row
    )


# ============================================================
# DATABASE REPAIR / SETUP
# ============================================================

TABLES = [
    "users",
    "attendance",
    "faculty_attendance",
    "assignments",
    "submissions",
    "notices",
    "results",
    "fees",
    "placements",
    "timetable",
]


def prepare_database():
    """
    Makes existing BIGINT id columns auto-generate IDs.

    This fixes:
    - Add Student
    - Add Faculty
    - Create Assignment
    - Add Result
    - Add Notice
    - Attendance
    - Faculty Attendance
    - Assignment Submission

    Also adds columns required for real uploaded files.
    """

    with db() as conn:

        # ----------------------------------------------------
        # Make existing ID columns identity columns
        # ----------------------------------------------------

        for table in TABLES:

            try:
                identity = conn.execute(
                    """
                    SELECT a.attidentity
                    FROM pg_attribute a
                    JOIN pg_class c
                      ON c.oid = a.attrelid
                    WHERE c.relname = %s
                      AND a.attname = 'id'
                      AND a.attnum > 0
                      AND NOT a.attisdropped
                    """,
                    (table,)
                ).fetchone()

                if identity and identity["attidentity"] == "":
                    conn.execute(
                        f"""
                        ALTER TABLE {table}
                        ALTER COLUMN id
                        ADD GENERATED BY DEFAULT AS IDENTITY
                        """
                    )

            except Exception as exc:
                print(
                    f"Identity setup warning for {table}: {exc}"
                )

        # ----------------------------------------------------
        # Submission file storage
        # ----------------------------------------------------

        conn.execute(
            """
            ALTER TABLE submissions
            ADD COLUMN IF NOT EXISTS file_data BYTEA
            """
        )

        conn.execute(
            """
            ALTER TABLE submissions
            ADD COLUMN IF NOT EXISTS mime_type TEXT
            """
        )

        conn.execute(
            """
            ALTER TABLE submissions
            ADD COLUMN IF NOT EXISTS file_size BIGINT
            """
        )

        conn.execute(
            """
            ALTER TABLE submissions
            ADD COLUMN IF NOT EXISTS student_notes TEXT
            """
        )

        # ----------------------------------------------------
        # Synchronize identity sequences with existing IDs
        # ----------------------------------------------------

        for table in TABLES:

            try:

                sequence = conn.execute(
                    """
                    SELECT pg_get_serial_sequence(
                        %s,
                        'id'
                    ) AS sequence
                    """,
                    (table,)
                ).fetchone()

                if sequence and sequence["sequence"]:

                    maximum = conn.execute(
                        f"""
                        SELECT COALESCE(MAX(id), 0) AS maximum
                        FROM {table}
                        """
                    ).fetchone()["maximum"]

                    if maximum and int(maximum) > 0:

                        conn.execute(
                            """
                            SELECT setval(
                                %s::regclass,
                                %s,
                                true
                            )
                            """,
                            (
                                sequence["sequence"],
                                int(maximum),
                            )
                        )

            except Exception as exc:
                print(
                    f"Sequence setup warning for {table}: {exc}"
                )

        conn.commit()


@app.on_event("startup")
def startup():
    print("Preparing PostgreSQL database...")
    prepare_database()
    print("PostgreSQL database ready.")


# ============================================================
# HELPERS
# ============================================================

def rows(table):

    allowed = {
        "users",
        "attendance",
        "faculty_attendance",
        "assignments",
        "submissions",
        "notices",
        "results",
        "fees",
        "placements",
        "timetable",
    }

    if table not in allowed:
        raise ValueError("Invalid table")

    with db() as conn:

        return conn.execute(
            f"""
            SELECT *
            FROM {table}
            ORDER BY id
            """
        ).fetchall()


def clean(v):

    if isinstance(v, (datetime, date)):
        return v.isoformat()

    return v


def clean_rows(items):

    cleaned = []

    for item in items:

        row = {}

        for key, value in dict(item).items():

            # Never send the actual binary file
            # through /api/state.
            if key == "file_data":
                continue

            row[key] = clean(value)

        cleaned.append(row)

    return cleaned


# ============================================================
# REQUEST MODELS
# ============================================================

class LoginRequest(BaseModel):

    email: str
    password: str


class AttendanceRequest(BaseModel):

    student_id: int
    subject: str
    present: bool
    date: Optional[str] = None


class FacultyAttendanceRequest(BaseModel):

    faculty_id: int
    present: bool
    date: Optional[str] = None


class AssignmentRequest(BaseModel):

    title: str
    subject: str
    description: str = ""
    due_date: str
    max_marks: int = 20
    created_by: int


class SubmissionRequest(BaseModel):

    assignment_id: int
    student_id: int
    submitted_at: Optional[str] = None
    file_name: str = "submission.pdf"
    student_notes: str = ""


class GradeRequest(BaseModel):

    marks: float
    feedback: str = ""


class NoticeRequest(BaseModel):

    title: str
    body: str
    category: str = "General"
    author: str = "Academic Office"


class UserRequest(BaseModel):

    name: str
    email: str
    password: str = "1234"
    role: str

    department: Optional[str] = None
    class_year: Optional[str] = None
    roll_no: Optional[str] = None
    employee_id: Optional[str] = None
    phone: Optional[str] = None

    status: str = "Active"


class FeeRequest(BaseModel):

    student_id: int
    amount: float


class ResultRequest(BaseModel):

    student_id: int
    subject: str
    internal: float
    external: float
    total: float
    grade: str
    published: int = 1
    published_by: Optional[int] = None


# ============================================================
# LOGIN ALIASES
# ============================================================

ALIASES = {

    "student0001@gmail.com":
        "nikki@unisphere.edu",

    "student0002@gmail.com":
        "aarav@gmail.com",

    "student0003@gmail.com":
        "meera@gmail.com",

    "student0004@gmail.com":
        "kabir@gmail.com",

    "faculty01@gmail.com":
        "priya@unisphere.edu",

    "faculty02@gmail.com":
        "rajesh@unisphere.edu",
}


# ============================================================
# HEALTH
# ============================================================

@app.get("/api/health")
def health():

    with db() as conn:

        conn.execute("SELECT 1")

    return {
        "status": "ok",
        "database": "postgresql"
    }


# ============================================================
# LOGIN
# ============================================================

@app.post("/api/login")
def login(payload: LoginRequest):

    email = payload.email.strip().lower()

    email = ALIASES.get(
        email,
        email
    )

    with db() as conn:

        user = conn.execute(
            """
            SELECT *
            FROM users
            WHERE LOWER(email)=LOWER(%s)
              AND password=%s
            LIMIT 1
            """,
            (
                email,
                payload.password
            )
        ).fetchone()

    if not user:

        raise HTTPException(
            status_code=401,
            detail="Invalid email or password"
        )

    return clean_rows([user])[0]


# ============================================================
# STATE
# ============================================================

@app.get("/api/state")
def state():

    with db() as conn:

        users = conn.execute(
            """
            SELECT *
            FROM users
            ORDER BY id
            """
        ).fetchall()

        attendance = conn.execute(
            """
            SELECT
                id,
                student_id,
                subject,
                date,
                present
            FROM attendance
            ORDER BY id
            """
        ).fetchall()

        faculty_attendance = conn.execute(
            """
            SELECT
                id,
                faculty_id,
                date,
                present
            FROM faculty_attendance
            ORDER BY id
            """
        ).fetchall()

        assignments = conn.execute(
            """
            SELECT
                a.*,
                u.name AS creator_name
            FROM assignments a
            LEFT JOIN users u
              ON u.id = a.created_by
            ORDER BY a.id DESC
            """
        ).fetchall()

        submissions = conn.execute(
            """
            SELECT
                s.id,
                s.assignment_id,
                s.student_id,
                s.submitted_at,
                s.file_name,
                s.status,
                s.marks,
                s.feedback,
                s.mime_type,
                s.file_size,
                s.student_notes,

                u.name AS student_name,
                u.roll_no,
                u.email AS student_email,

                a.title AS assignment_title,
                a.subject,
                a.created_by AS assignment_faculty_id

            FROM submissions s

            LEFT JOIN users u
              ON u.id = s.student_id

            LEFT JOIN assignments a
              ON a.id = s.assignment_id

            ORDER BY s.id DESC
            """
        ).fetchall()

        notices = conn.execute(
            """
            SELECT *
            FROM notices
            ORDER BY id DESC
            """
        ).fetchall()

        results = conn.execute(
            """
            SELECT
                r.*,
                u.name AS student_name,
                u.roll_no
            FROM results r
            LEFT JOIN users u
              ON u.id = r.student_id
            ORDER BY r.id DESC
            """
        ).fetchall()

        fees = conn.execute(
            """
            SELECT
                f.*,
                u.name AS student_name,
                u.email,
                u.roll_no,
                u.department
            FROM fees f
            LEFT JOIN users u
              ON u.id = f.student_id
            ORDER BY f.id
            """
        ).fetchall()

        placements = conn.execute(
            """
            SELECT *
            FROM placements
            ORDER BY id
            """
        ).fetchall()

        timetable = conn.execute(
            """
            SELECT *
            FROM timetable
            ORDER BY id
            """
        ).fetchall()

    return {

        "users":
            clean_rows(users),

        "attendance":
            clean_rows(attendance),

        "faculty_attendance":
            clean_rows(faculty_attendance),

        "assignments":
            clean_rows(assignments),

        "submissions":
            clean_rows(submissions),

        "notices":
            clean_rows(notices),

        "results":
            clean_rows(results),

        "fees":
            clean_rows(fees),

        "placements":
            clean_rows(placements),

        "timetable":
            clean_rows(timetable),
    }


# ============================================================
# ATTENDANCE
# ============================================================

@app.get("/api/attendance/{student_id}")
def student_attendance(student_id: int):

    with db() as conn:

        data = conn.execute(
            """
            SELECT
                subject,
                COUNT(*)::int AS total,
                SUM(
                    CASE
                        WHEN present
                        THEN 1
                        ELSE 0
                    END
                )::int AS present

            FROM attendance

            WHERE student_id=%s

            GROUP BY subject

            ORDER BY subject
            """,
            (student_id,)
        ).fetchall()

    result = []

    for r in data:

        total = int(
            r["total"] or 0
        )

        present = int(
            r["present"] or 0
        )

        result.append({

            "subject":
                r["subject"],

            "total":
                total,

            "present":
                present,

            "percentage":
                round(
                    (present / total) * 100,
                    1
                )
                if total
                else 0,
        })

    return result


@app.post("/api/attendance")
def mark_attendance(
    payload: AttendanceRequest
):

    day = (
        payload.date
        or datetime.now().date().isoformat()
    )

    with db() as conn:

        existing = conn.execute(
            """
            SELECT id
            FROM attendance
            WHERE student_id=%s
              AND subject=%s
              AND date=%s
            LIMIT 1
            """,
            (
                payload.student_id,
                payload.subject,
                day
            )
        ).fetchone()

        if existing:

            row = conn.execute(
                """
                UPDATE attendance

                SET present=%s

                WHERE id=%s

                RETURNING *
                """,
                (
                    payload.present,
                    existing["id"]
                )
            ).fetchone()

        else:

            row = conn.execute(
                """
                INSERT INTO attendance
                (
                    student_id,
                    subject,
                    date,
                    present
                )

                VALUES
                (
                    %s,%s,%s,%s
                )

                RETURNING *
                """,
                (
                    payload.student_id,
                    payload.subject,
                    day,
                    payload.present
                )
            ).fetchone()

    return clean_rows([row])[0]


# ============================================================
# FACULTY ATTENDANCE
# ============================================================

@app.get("/api/faculty-attendance")
def get_faculty_attendance():

    return clean_rows(
        rows("faculty_attendance")
    )


@app.post("/api/faculty-attendance")
def mark_faculty_attendance(
    payload: FacultyAttendanceRequest
):

    day = (
        payload.date
        or datetime.now().date().isoformat()
    )

    with db() as conn:

        existing = conn.execute(
            """
            SELECT id
            FROM faculty_attendance
            WHERE faculty_id=%s
              AND date=%s
            LIMIT 1
            """,
            (
                payload.faculty_id,
                day
            )
        ).fetchone()

        if existing:

            row = conn.execute(
                """
                UPDATE faculty_attendance
                SET present=%s
                WHERE id=%s
                RETURNING *
                """,
                (
                    payload.present,
                    existing["id"]
                )
            ).fetchone()

        else:

            row = conn.execute(
                """
                INSERT INTO faculty_attendance
                (
                    faculty_id,
                    date,
                    present
                )

                VALUES
                (
                    %s,%s,%s
                )

                RETURNING *
                """,
                (
                    payload.faculty_id,
                    day,
                    payload.present
                )
            ).fetchone()

    return clean_rows([row])[0]


# ============================================================
# RESULTS
# ============================================================

@app.post("/api/results")
def create_result(
    payload: ResultRequest
):

    with db() as conn:

        row = conn.execute(
            """
            INSERT INTO results
            (
                student_id,
                subject,
                internal,
                external,
                total,
                grade,
                published
            )

            VALUES
            (
                %s,%s,%s,%s,%s,%s,%s
            )

            RETURNING *
            """,
            (
                payload.student_id,
                payload.subject,
                payload.internal,
                payload.external,
                payload.total,
                payload.grade,
                bool(payload.published)
            )
        ).fetchone()

    return clean_rows([row])[0]


# ============================================================
# ASSIGNMENTS
# ============================================================

@app.post("/api/assignments")
def create_assignment(
    payload: AssignmentRequest
):

    created = (
        datetime.now()
        .date()
        .isoformat()
    )

    with db() as conn:

        # Verify faculty/user exists
        creator = conn.execute(
            """
            SELECT id
            FROM users
            WHERE id=%s
            LIMIT 1
            """,
            (payload.created_by,)
        ).fetchone()

        if not creator:

            raise HTTPException(
                status_code=400,
                detail="Creator user not found"
            )

        row = conn.execute(
            """
            INSERT INTO assignments
            (
                title,
                subject,
                description,
                due_date,
                max_marks,
                created_by,
                created_at
            )

            VALUES
            (
                %s,%s,%s,%s,%s,%s,%s
            )

            RETURNING *
            """,
            (
                payload.title,
                payload.subject,
                payload.description,
                payload.due_date,
                payload.max_marks,
                payload.created_by,
                created
            )
        ).fetchone()

    return clean_rows([row])[0]


# ============================================================
# SUBMISSION - JSON FALLBACK
# ============================================================

@app.post("/api/submissions")
def create_submission(
    payload: SubmissionRequest
):

    submitted = (
        payload.submitted_at
        or datetime.now().isoformat(
            timespec="seconds"
        )
    )

    with db() as conn:

        assignment = conn.execute(
            """
            SELECT *
            FROM assignments
            WHERE id=%s
            """,
            (payload.assignment_id,)
        ).fetchone()

        if not assignment:

            raise HTTPException(
                status_code=404,
                detail="Assignment not found"
            )

        student = conn.execute(
            """
            SELECT *
            FROM users
            WHERE id=%s
            AND role='student'
            """,
            (payload.student_id,)
        ).fetchone()

        if not student:

            raise HTTPException(
                status_code=404,
                detail="Student not found"
            )

        row = conn.execute(
            """
            INSERT INTO submissions
            (
                assignment_id,
                student_id,
                submitted_at,
                file_name,
                status,
                marks,
                feedback,
                student_notes
            )

            VALUES
            (
                %s,%s,%s,%s,
                'Submitted',
                NULL,
                NULL,
                %s
            )

            RETURNING *
            """,
            (
                payload.assignment_id,
                payload.student_id,
                submitted,
                payload.file_name,
                payload.student_notes
            )
        ).fetchone()

    return clean_rows([row])[0]


# ============================================================
# REAL FILE UPLOAD
# ============================================================

@app.post(
    "/api/assignments/{assignment_id}/submit"
)
async def upload_assignment(
    assignment_id: int,
    student_id: int = Form(...),
    student_notes: str = Form(""),
    file: UploadFile = File(...)
):

    # --------------------------------------------------------
    # Maximum upload size: 5 MB
    # --------------------------------------------------------

    MAX_SIZE = 5 * 1024 * 1024

    file_data = await file.read()

    if not file_data:

        raise HTTPException(
            status_code=400,
            detail="The uploaded file is empty."
        )

    if len(file_data) > MAX_SIZE:

        raise HTTPException(
            status_code=413,
            detail="File is too large. Maximum size is 5 MB."
        )

    # --------------------------------------------------------
    # Verify file type
    # --------------------------------------------------------

    allowed_extensions = {
        ".pdf",
        ".doc",
        ".docx",
        ".zip",
        ".txt",
        ".ppt",
        ".pptx",
        ".xls",
        ".xlsx",
        ".csv",
        ".jpg",
        ".jpeg",
        ".png",
        ".webp",
    }

    filename = (
        file.filename
        or "submission"
    )

    filename = (
        filename
        .replace('"', "")
        .replace("\r", "")
        .replace("\n", "")
)

    extension = os.path.splitext(
        filename
    )[1].lower()

    if extension not in allowed_extensions:

        raise HTTPException(
            status_code=400,
            detail=(
                "Unsupported file type. "
                "Allowed: PDF, DOC, DOCX, ZIP, "
                "PPT, PPTX, XLS, XLSX, CSV, "
                "TXT and common images."
            )
        )

    # --------------------------------------------------------
    # Verify assignment + student
    # --------------------------------------------------------

    with db() as conn:

        assignment = conn.execute(
            """
            SELECT *
            FROM assignments
            WHERE id=%s
            """,
            (assignment_id,)
        ).fetchone()

        if not assignment:

            raise HTTPException(
                status_code=404,
                detail="Assignment not found"
            )

        student = conn.execute(
            """
            SELECT *
            FROM users
            WHERE id=%s
              AND role='student'
            """,
            (student_id,)
        ).fetchone()

        if not student:

            raise HTTPException(
                status_code=404,
                detail="Student not found"
            )

        # ----------------------------------------------------
        # Prevent accidental duplicate submission
        # ----------------------------------------------------

        existing = conn.execute(
            """
            SELECT id
            FROM submissions
            WHERE assignment_id=%s
              AND student_id=%s
            ORDER BY id DESC
            LIMIT 1
            """,
            (
                assignment_id,
                student_id
            )
        ).fetchone()

        submitted = datetime.now().isoformat(
            timespec="seconds"
        )

        if existing:

            row = conn.execute(
                """
                UPDATE submissions

                SET
                    submitted_at=%s,
                    file_name=%s,
                    status='Submitted',
                    marks=NULL,
                    feedback=NULL,
                    file_data=%s,
                    mime_type=%s,
                    file_size=%s,
                    student_notes=%s

                WHERE id=%s

                RETURNING *
                """,
                (
                    submitted,
                    filename,
                    file_data,
                    file.content_type
                    or "application/octet-stream",
                    len(file_data),
                    student_notes,
                    existing["id"]
                )
            ).fetchone()

        else:

            row = conn.execute(
                """
                INSERT INTO submissions
                (
                    assignment_id,
                    student_id,
                    submitted_at,
                    file_name,
                    status,
                    marks,
                    feedback,
                    file_data,
                    mime_type,
                    file_size,
                    student_notes
                )

                VALUES
                (
                    %s,
                    %s,
                    %s,
                    %s,
                    'Submitted',
                    NULL,
                    NULL,
                    %s,
                    %s,
                    %s,
                    %s
                )

                RETURNING *
                """,
                (
                    assignment_id,
                    student_id,
                    submitted,
                    filename,
                    file_data,
                    file.content_type
                    or "application/octet-stream",
                    len(file_data),
                    student_notes
                )
            ).fetchone()

    return clean_rows([row])[0]


# ============================================================
# DOWNLOAD SUBMISSION
# ============================================================

@app.get(
    "/api/submissions/{submission_id}/file"
)
def download_submission(
    submission_id: int
):

    with db() as conn:

        row = conn.execute(
            """
            SELECT
                file_data,
                file_name,
                mime_type
            FROM submissions
            WHERE id=%s
            """,
            (submission_id,)
        ).fetchone()

    if not row:

        raise HTTPException(
            status_code=404,
            detail="Submission not found"
        )

    if not row["file_data"]:

        raise HTTPException(
            status_code=404,
            detail="No uploaded file exists."
        )

    filename = (
        row["file_name"]
        or "submission"
    )

    mime = (
        row["mime_type"]
        or "application/octet-stream"
    )

    return Response(
        content=bytes(row["file_data"]),
        media_type=mime,
        headers={
            "Content-Disposition":
                f'attachment; filename="{filename}"'
        }
    )


# ============================================================
# GRADE SUBMISSION
# ============================================================

@app.put(
    "/api/submissions/{submission_id}/grade"
)
def grade_submission(
    submission_id: int,
    payload: GradeRequest
):

    with db() as conn:

        row = conn.execute(
            """
            UPDATE submissions

            SET
                marks=%s,
                feedback=%s,
                status='Graded'

            WHERE id=%s

            RETURNING *
            """,
            (
                payload.marks,
                payload.feedback,
                submission_id
            )
        ).fetchone()

    if not row:

        raise HTTPException(
            status_code=404,
            detail="Submission not found"
        )

    return clean_rows([row])[0]


# ============================================================
# NOTICES
# ============================================================

@app.post("/api/notices")
def create_notice(
    payload: NoticeRequest
):

    created = (
        datetime.now()
        .date()
        .isoformat()
    )

    with db() as conn:

        row = conn.execute(
            """
            INSERT INTO notices
            (
                title,
                body,
                category,
                author,
                created_at
            )

            VALUES
            (
                %s,%s,%s,%s,%s
            )

            RETURNING *
            """,
            (
                payload.title,
                payload.body,
                payload.category,
                payload.author,
                created
            )
        ).fetchone()

    return clean_rows([row])[0]


# ============================================================
# USERS
# ============================================================

@app.post("/api/users")
def create_user(
    payload: UserRequest
):

    with db() as conn:

        exists = conn.execute(
            """
            SELECT id
            FROM users
            WHERE LOWER(email)=LOWER(%s)
            """,
            (payload.email,)
        ).fetchone()

        if exists:

            raise HTTPException(
                status_code=409,
                detail="Email already exists"
            )

        row = conn.execute(
            """
            INSERT INTO users
            (
                name,
                email,
                password,
                role,
                department,
                class_year,
                roll_no,
                employee_id,
                phone,
                status
            )

            VALUES
            (
                %s,%s,%s,%s,%s,
                %s,%s,%s,%s,%s
            )

            RETURNING *
            """,
            (
                payload.name,
                payload.email,
                payload.password,
                payload.role,
                payload.department,
                payload.class_year,
                payload.roll_no,
                payload.employee_id,
                payload.phone,
                payload.status
            )
        ).fetchone()

    return clean_rows([row])[0]


@app.delete("/api/users/{user_id}")
def delete_user(
    user_id: int
):

    with db() as conn:

        row = conn.execute(
            """
            DELETE FROM users
            WHERE id=%s
            RETURNING id
            """,
            (user_id,)
        ).fetchone()

    if not row:

        raise HTTPException(
            status_code=404,
            detail="User not found"
        )

    return {
        "ok": True,
        "id": user_id
    }


# ============================================================
# FEES
# ============================================================

@app.get("/api/fees")
def get_fees():

    with db() as conn:

        data = conn.execute(
            """
            SELECT
                f.*,
                u.name AS student_name,
                u.email,
                u.roll_no,
                u.department

            FROM fees f

            LEFT JOIN users u
              ON u.id=f.student_id

            ORDER BY f.id
            """
        ).fetchall()

    return clean_rows(data)


@app.get("/api/fees/{student_id}")
def get_student_fee(
    student_id: int
):

    with db() as conn:

        row = conn.execute(
            """
            SELECT
                f.*,
                u.name AS student_name,
                u.email,
                u.roll_no,
                u.department

            FROM fees f

            LEFT JOIN users u
              ON u.id=f.student_id

            WHERE f.student_id=%s

            LIMIT 1
            """,
            (student_id,)
        ).fetchone()

    if not row:

        raise HTTPException(
            status_code=404,
            detail="Fee record not found"
        )

    return clean_rows([row])[0]


@app.post("/api/fees/pay")
def pay_fee(
    payload: FeeRequest
):

    if payload.amount <= 0:

        raise HTTPException(
            status_code=400,
            detail="Amount must be positive"
        )

    with db() as conn:

        row = conn.execute(
            """
            UPDATE fees

            SET paid =
                LEAST(
                    semester_fee,
                    paid + %s
                )

            WHERE student_id=%s

            RETURNING *
            """,
            (
                payload.amount,
                payload.student_id
            )
        ).fetchone()

    if not row:

        raise HTTPException(
            status_code=404,
            detail="Fee record not found"
        )

    return clean_rows([row])[0]


# ============================================================
# ADMIN ANALYTICS
# ============================================================

@app.get("/api/admin/analytics")
def admin_analytics():

    with db() as conn:

        users = conn.execute(
            """
            SELECT

                COUNT(*)
                FILTER (
                    WHERE role='student'
                )::int AS students,

                COUNT(*)
                FILTER (
                    WHERE role='faculty'
                )::int AS faculty,

                COUNT(*)
                FILTER (
                    WHERE role='admin'
                )::int AS admins,

                COUNT(*)::int AS total

            FROM users
            """
        ).fetchone()

        fee = conn.execute(
            """
            SELECT
                COALESCE(
                    SUM(semester_fee),
                    0
                ) AS total_fees,

                COALESCE(
                    SUM(paid),
                    0
                ) AS collected

            FROM fees
            """
        ).fetchone()

        attendance = conn.execute(
            """
            SELECT

                COUNT(*)::int AS total,

                COALESCE(
                    SUM(
                        CASE
                            WHEN present
                            THEN 1
                            ELSE 0
                        END
                    ),
                    0
                )::int AS present

            FROM attendance
            """
        ).fetchone()

    total = int(
        attendance["total"] or 0
    )

    present = int(
        attendance["present"] or 0
    )

    return {

        **dict(users),

        "total_fees":
            float(
                fee["total_fees"] or 0
            ),

        "collected":
            float(
                fee["collected"] or 0
            ),

        "attendance_percentage":
            round(
                present / total * 100,
                1
            )
            if total
            else 0,
    }